### ISSUE TITLE
Longitude values beyond a 360-degree range

### ISSUE THREAD

**Issue by fitzyjoe** [GenericMappingTools/gmt-gshhg#10]
There are longitude values in the range of [-180,360].  While not necessarily illegal, it's strange.

When I tried to run a query in MySQL 8 against the field that is of type POLYGON, I get an error:

`A parameter of function st_contains contains a geometry with longitude 180.004972, which is out of range. It must be within (-180.000000, 180.000000].`

I know this MySQL problem isn't a concern of this library, but I wanted to at least give others a heads up of the range of values and the problem they might encounter if they load the data.

**Comment by PaulWessel** [comment]
It is only strange in a Cartesian GIS world where polygons straddling the date line  are broken into two.  The Eurasia polygon goes from -17 to 192 in longitude.  We are not breaking it up as GMT has no problem handling that as a single geo-polygon.
However, I can imagine adding some more commentary to the README to make it clear that this is a spherical dataset.

**Comment by Esteban82** [comment]
This can this be closed, right?

**Comment by joa-quim** [comment]
Yes, I think so
