### ISSUE TITLE
Source value 'c'

### ISSUE THREAD

**Issue by fitzyjoe** [GenericMappingTools/gmt-gshhg#9]
I was extracting information from gshhg v2.3.7 and ran across 4 distinct values for source:

source code with count
```
W: 179825
C: 8058
A: 673
c: 56
```

Commands I used to obtain those numbers:
```
gmt gshhg gshhs_f.b | grep '>' | tr -s ' ' | cut -d ' ' -f5 | grep W  | wc
gmt gshhg gshhs_f.b | grep '>' | tr -s ' ' | cut -d ' ' -f5 | grep C  | wc
gmt gshhg gshhs_f.b | grep '>' | tr -s ' ' | cut -d ' ' -f5 | grep A  | wc
gmt gshhg gshhs_f.b | grep '>' | tr -s ' ' | cut -d ' ' -f5 | grep c  | wc
```

I found docs on this page: https://docs.generic-mapping-tools.org/latest/supplements/gshhg/gshhg.html

It says, "Source is either W (World Vector Shoreline) or C (CIA World Data Bank II)"

I found this page: https://www.soest.hawaii.edu/pwessel/gshhg/

It lists the sources as:

[World Vector Shorelines](http://shoreline.noaa.gov/data/datasheets/wvs.html) (WVS).
[CIA World Data Bank II](http://www.evl.uic.edu/pape/data/WDB) (WDBII).
[Atlas of the Cryosphere](http://nsidc.org/data/atlas/) (AC).

So, I'm guessing that A means "Atlas of the Cryosphere".  **Anyone know what lowercase 'c' means?**  Is it the same as uppercase 'C'?

**Comment by PaulWessel** [comment]
I see the gshhg man page needs some updating to mention A - thanks. As for lower case c, the GMT gshhg man page says

> Source is either W (World Vector Shoreline) or C (CIA World Data Bank II); lower case is used if a lake is a river-lake

so those are areas of rivers that are too wide to be a "line".

**Comment by PaulWessel** [comment]
I have improved the gshhg GMT man page to include mention of the Atlas and A.
